### ISSUE TITLE
File attachment support (outside of images)

### ISSUE THREAD

**Issue by ghost** [Echoshard/Gemini_Discordbot#11]
Recently Google updated the Gemini API in AI studio to support files (e.g: PDFs) other than images. Is it possible to add this to your bot? since one time ago before the update was released, I tried to add pdf/txt support to your code with Bard/Gemini's help but it failed.

**Comment by Echoshard** [comment]
I will be working on this this weekend along with the threads request I saw. I have had trouble with file upload so far

**Comment by hihumanzone** [comment]
The project blew up, great work ♥️

**Comment by aarushkomaar** [comment]
Any updates? In my use case, users will likely upload very long text messages which automatically become .txt files on Discord. Although the bot recognizes and does in fact start typing, after some time, the typing just stops and there is no response. Would love if .txt and .pdf files would just work as smoothly as text and images do. 

Appreciate the work, you helped me out so much with this!

**Comment by hihumanzone** [comment]
> Recently Google updated the Gemini API in AI studio to support files (e.g: PDFs) other than images. Is it possible to add this to your bot? since one time ago before the update was released, I tried to add pdf/txt support to your code with Bard/Gemini's help but it failed.

Looking at the supported file formats mentioned here: https://ai.google.dev/gemini-api/docs/prompting_with_media?lang=python. It seems that PDFs are not supported.

**Comment by Echoshard** [comment]
> > Recently Google updated the Gemini API in AI studio to support files (e.g: PDFs) other than images. Is it possible to add this to your bot? since one time ago before the update was released, I tried to add pdf/txt support to your code with Bard/Gemini's help but it failed.
> 
> Looking at the supported file formats mentioned here: https://ai.google.dev/gemini-api/docs/prompting_with_media?lang=python. It seems that PDFs are not supported.

Cause it's discord I don't think I will actually use the file API.  Instead I will just support PDF (Then just convert them to text) and text files. 

I will be adding web scraping and you tube summary from the transcript.

**Comment by hihumanzone** [comment]
> > Looking at the supported file formats mentioned here: https://ai.google.dev/gemini-api/docs/prompting_with_media?lang=python. It seems that PDFs are not supported.
> 
> Cause it's discord I don't think I will actually use the file API. Instead I will just support PDF (Then just convert them to text) and text files.
> 
> I will be adding web scraping and you tube summary from the transcript.

Ohk, cool. that works too.
Thank you!

**Comment by SimplifyMe69** [comment]
Alright, that's perfect. Thanks a lot!

**Comment by SimplifyMe69** [comment]
> Alright, that's perfect. Thanks a lot!



> > > Recently Google updated the Gemini API in AI studio to support files (e.g: PDFs) other than images. Is it possible to add this to your bot? since one time ago before the update was released, I tried to add pdf/txt support to your code with Bard/Gemini's help but it failed.
> > 
> > 
> > Looking at the supported file formats mentioned here: https://ai.google.dev/gemini-api/docs/prompting_with_media?lang=python. It seems that PDFs are not supported.
> 
> Cause it's discord I don't think I will actually use the file API. Instead I will just support PDF (Then just convert them to text) and text files.
> 
> I will be adding web scraping and you tube summary from the transcript.

Alright, that's perfect. Thanks a lot!

**Comment by SimplifyMe69** [comment]
> > > Recently Google updated the Gemini API in AI studio to support files (e.g: PDFs) other than images. Is it possible to add this to your bot? since one time ago before the update was released, I tried to add pdf/txt support to your code with Bard/Gemini's help but it failed.
> > 
> > 
> > Looking at the supported file formats mentioned here: https://ai.google.dev/gemini-api/docs/prompting_with_media?lang=python. It seems that PDFs are not supported.
> 
> Cause it's discord I don't think I will actually use the file API. Instead I will just support PDF (Then just convert them to text) and text files.
> 
> I will be adding web scraping and you tube summary from the transcript.

Alright, that's perfect. Thanks a lot!

**Comment by aarushkomaar** [comment]
> Cause it's discord I don't think I will actually use the file API. Instead I will just support PDF (Then just convert them to text) and text files.
> 
> I will be adding web scraping and you tube summary from the transcript.

Alright, that's perfect. Thanks a lot!

**Comment by Echoshard** [comment]
@SimplifyMe69  @hihumanzone  @Spicytin  I updated it so you should have everything you need!
