### ISSUE TITLE
System Instructions?

### ISSUE THREAD

**Issue by lugnutoralc** [Echoshard/Gemini_Discordbot#13]
Is there a way to incorporate the System Instructions / System Prompt?

**Comment by Echoshard** [comment]
I have found Gemini is pretty bad at doing system prompts but I saw Gemini Pro now lets you insert one still did not do what I wanted a lot of the time.

I found adding the first message in it's history you get Tell it the System Prompt and the user part being "Understood"

Now that gemini is around for everyone I will add the prompt if it works right in python

**Comment by Echoshard** [comment]
I upgraded the bot to use Gemini - Flash so you have access to a system prompt for the image and the text system.
