### ISSUE TITLE
Idk what I'm doing wrong

### ISSUE THREAD

**Issue by AmazingZach** [Echoshard/Gemini_Discordbot#16]
![image](https://github.com/user-attachments/assets/789e8971-448e-4581-95c7-0415559d2591)

**Comment by Echoshard** [comment]
Did you change the max History at all?  It needs to be setup like MAX_HISTORY = 10 not MAX_HISTORY = "10"

**Comment by AmazingZach** [comment]
Ohhhh I see, thank you!
