### ISSUE TITLE
[Feature request]Request to add network proxy settings to the program

### ISSUE THREAD

**Issue by AlanBacker** [Echoshard/Gemini_Discordbot#5]
Hi dear developer
This is a good project, but due to Google's rigid requirements, the IP of the server calling the Gemini Pro API must be a clean IP address in the region that Google requires. I think the IPs of many cloud servers will be blocked by Google. For example, I am using a Racknerd server. Although the physical address of the server is in the United States, it will still display "Address Unavailable", so this will make it more difficult for me. One suggestion I have is that I hope the program can add relevant network proxy settings. I think this will be a great feature!

**Comment by Echoshard** [comment]
Discord.py does not appear to support proxy settings.
