### ISSUE TITLE
Message History not Working

### ISSUE THREAD

**Issue by sarthakjainxyz** [Echoshard/Gemini_Discordbot#8]
It is not saving the history in `message_history = {}` (i havent disabled it in .env it is more than 0)

**Comment by Echoshard** [comment]
Are you talking to it in Images? And did you debug the message_history to check?

**Comment by sarthakjainxyz** [comment]
> Are you talking to it in Images? And did you debug the message_history to check?


no its not in images, and i tried to debug it but it doesnt save the history anywhere  (this is console debug screenshot)
![image_2023-12-28_094417556](https://github.com/Echoshard/Gemini_Discordbot/assets/88922662/978030fc-d16a-4e1c-9f9d-b64007caa52d)

**Comment by Echoshard** [comment]
I think you miss understand message history is for sending back to the LLM like a conversation. The history is saved inside of message history per user, it does not output to any file. But that's pretty easy to do.  

Here is an example of how the history works I get two facts about cats dogs and lizards without needing to reprompt it. 
![image](https://github.com/Echoshard/Gemini_Discordbot/assets/6569522/ca4891ad-07a5-49fd-aac6-0ab3a23d6452)

**Comment by sarthakjainxyz** [comment]
ohh, i thought maybe as like context in VertexAI i can same some promts in it

**Comment by Echoshard** [comment]
Not to worry, You should be able to easily output it to a file if you want however.
