### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by realbullett** [Echoshard/Gemini_Discordbot#9]
Could you please post another version of this project but without User Message History Management? I'm trying to remove it so each messages from any user will be remembered and the same data from previous user to be available for other users instead of user-specific history.

Please do the need, I have tried doing it but I couldn't make it happen, thanks!

**Comment by realbullett** [comment]
You don't have to post another version, but please help me

**Comment by Echoshard** [comment]
In update_message_history 

add   `user_id = "ForcedID"` and it will put everyone on the same ID 

```
def update_message_history(user_id, text):
    # ForceUserID
    user_id = "ForcedID"
    # Check if user_id already exists in the dictionary
    if user_id in message_history:
        # Append the new message to the user's message list
        message_history[user_id].append(text)
        # If there are more than 12 messages, remove the oldest one
        if len(message_history[user_id]) > MAX_HISTORY:
            message_history[user_id].pop(0)
    else:
        # If the user_id does not exist, create a new entry with the message
        message_history[user_id] = [text]
```

**Comment by realbullett** [comment]
The AI does not reply as intended, please check the below screenshots
https://prnt.sc/rnoIwOV_lnYb
https://prnt.sc/iyzoedjXp6lV

**Comment by Echoshard** [comment]
I am sorry I do not understand what you were trying to get it to say.  A note it's not using the chat protocol it's using the Text Generation one so it can be a bit unpredictable. 

my usual test is.

Tell me two facts about cats

Await Reply

and Dogs?

Await Reply 

and Lizards?

Does that work if three different people are chatting? 

![image](https://github.com/Echoshard/Gemini_Discordbot/assets/6569522/d210d765-1880-4555-a748-f61e3f121c8d)

**Comment by realbullett** [comment]
Imagine this scenario,

Built a custom Discord bot for my product's server, hoping it could handle support by learning from my input. But there's a snag: any data the bot learns from me is only available to me but remains hidden from users unless the other user trains it just like I did which makes it user-specific data, making it useless for their actual questions. How can I bridge this gap and share the bot's knowledge with everyone?

Check the image attached for better understanding
![Screenshot_20231229-013204_Discord](https://github.com/Echoshard/Gemini_Discordbot/assets/137709882/a1c7c1fc-0db5-48ba-865a-86038c56ae7d)
![Screenshot_20231229-013219_Discord](https://github.com/Echoshard/Gemini_Discordbot/assets/137709882/de5e50eb-80f5-4e0a-9bd9-97396d078bb5)

**Comment by realbullett** [comment]
By "supposed to be data I taught the bot", I mean the data provided by the bot to a random user is different from what I taught it

**Comment by realbullett** [comment]
If you still can't understand what I'm trying to explain, pls add me on discord -

no.me

**Comment by Echoshard** [comment]
O you want to do a Pre-prompt of data! This isn't really designed for that at all, You need to do it an entirely different way I added you on discord.
